### ISSUE TITLE
Failed to install 'cordova-plugin-ionic-webview': Error: Uh oh!

### ISSUE THREAD

**Issue by suwu150** [ionic-team/cordova-plugin-ionic-webview#557]
```
Failed to install 'cordova-plugin-ionic-webview': Error: Uh oh!
ENOENT: no such file or directory, open '/Users/testProject/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at install (/Users/testProject/platforms/ios/cordova/lib/plugman/pluginHandlers.js:197:36)
    at ActionStack.process (/Users/testProject/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/testProject/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/Users/testProject/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/Users/testProject/platforms/ios/cordova/Api.js:247:10)
    at handleInstall (/Users/xxxx/node/v10.20.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:10)
    at /Users/xxxx/node/v10.20.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:349:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
Uh oh!
ENOENT: no such file or directory, open '/Users/testProject/plugins/cordova-plugin-ionic-webview/src/www/ios/ios-wkwebview-exec.js'
> ionic cordova resources ios --force

```
cordova version :

```
9.0.0 (cordova-lib@9.0.1)
```
cordova-plugin-ionic-webview version "
```
    "cordova-plugin-ionic-webview": "^1.1.16",
```
i find this error when run ionic cordova platform add ios in command shell.What's the reason？

**Comment by jcesarmobile** [comment]
latest plugin version is 4.2.0, we don't support 1.x issues
