### ISSUE TITLE
apps using IonicWebViewEngine fails to load on pixel phones running android 14

### ISSUE THREAD

**Issue by mmfarahat** [ionic-team/cordova-plugin-ionic-webview#688]
Hello,
one of banking apps I am using started to crash on loading after upgrading to android 14 on pixel phones, according to the logs I think it may be casued by "com.ionicframework.cordova.webview.IonicWebViewEngine" package, here are the logs

> 11-29 07:46:26.749 15043 15043 D AndroidRuntime: Shutting down VM
11-29 07:46:26.749 15043 15043 E AndroidRuntime: FATAL EXCEPTION: main
11-29 07:46:26.749 15043 15043 E AndroidRuntime: Process: com.CIB.Digital.MB, PID: 15043
11-29 07:46:26.749 15043 15043 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~t0_kJSJyGc7dgB4WxiSJKQ==/com.CIB.Digital.MB-3mgj0iBoc3_okaX2LjN8_A==/lib/arm64/libtesting.so": -110
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1661)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at a.d.<clinit>(Unknown Source:2)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at com.ionicframework.cordova.webview.IonicWebViewEngine.<clinit>(Unknown Source:2)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.Class.forName(Class.java:536)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.Class.forName(Class.java:467)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at org.apache.cordova.CordovaWebViewImpl.createEngine(Unknown Source:12)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.makeWebViewEngine(Unknown Source:2)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.makeWebView(Unknown Source:2)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.init(Unknown Source:0)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.loadUrl(Unknown Source:4)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at com.CIB.Digital.MB.MainActivity.onCreate(Unknown Source:28)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8595)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8573)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8177)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-29 07:46:26.749 15043 15043 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
11-29 07:46:26.751  1537 15085 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-29 07:46:26.751  1537  2422 W ActivityTaskManager:   Force finishing activity com.CIB.Digital.MB/.MainActivity
11-29 07:46:26.752  1932  1956 V WindowManagerShell: Transition requested: android.os.BinderProxy@b371219 TransitionRequestInfo { type = CLOSE, triggerTask = null, remoteTransition = null, displayChange = null }
11-29 07:46:26.756 15043 15043 I Process : Sending signal. PID: 15043 SIG: 9
11-29 07:46:26.769  1537  2422 I ActivityManager: Process com.CIB.Digital.MB (pid 15043) has died: fg  TOP
11-29 07:46:26.769  1537  1654 I libprocessgroup: Successfully killed process cgroup uid 10359 pid 15043 in 0ms
11-29 07:46:26.769   883   883 I Zygote  : Process 15043 exited due to signal 9 (Killed)

**Comment by lewismunene020** [comment]
Hello.  .Did. you manage to. fix this error  ?
