### ISSUE TITLE
Failed to install 'cordova-plugin-ionic-webview':Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by johnnynode** [ionic-team/cordova-plugin-ionic-webview#81]
Error info:

```
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-ionic-webview@^1.1.16" via npm
Installing "cordova-plugin-ionic-webview" for android
Failed to install 'cordova-plugin-ionic-webview':Error: ENOENT: no such file or directory, open '/Users/../**/../platforms/android/assets/www/cordova_plugins.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at /Users/../**/../platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:137:12
    at _fulfilled (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/../**/../platforms/android/cordova/node_modules/q/q.js:877:14
    at runSingle (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/../**/../platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
Failed to restore plugin "cordova-plugin-ionic-webview" from config.xml. You might need to try adding it again. Error: Error: ENOENT: no such file or directory, open '/Users/../**/../platforms/android/assets/www/cordova_plugins.js'

```

Just like this case: https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/12

I have made a lot of changes in android platform, if I remove them, there would be a lot of trouble, is there any way to handle this error?

**Comment by johnnynode** [comment]
no response, will close this.

**Comment by JorgeOsorio97** [comment]
@johnnynode hi, how did you fixed it?
